# GeoPeril - A platform for the computation and web-mapping of hazard specific
# geospatial data, as well as for serving functionality to handle, share, and
# communicate threat specific information in a collaborative environment.
#
# Copyright (C) 2021 GFZ German Research Centre for Geosciences
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.
#
# Contributors:
#   Johannes Spazier (GFZ)
#   Sven Reissland (GFZ)
#   Martin Hammitzsch (GFZ)
#   Matthias RÃ¼ster (GFZ)
#   Hannes Fuchs (GFZ)

description: 'A platform for the computation and web-mapping of hazard specific geospatial data, as well as for serving functionality to handle, share, and communicate threat specific information in a collaborative environment.'

ignore paths:
  - '.*\.git/.*'
  - '.*\.reuse/.*'

comment in file:
  - '.*\.sh$'
  - '.*\.py$'
  - '.*\.yml$'
  - '.*\.toml$'
  - '.*\.md$'
  - '.*\.css$'
  - '.*\.sh$'
  - '.*\.js$'
  - '.*\.ts$'
  - '.*\.xml$'
  - '.*\.csv$'
  - '.*\.gitignore$'
  - '.*\.gitmodules$'
  - '.*Dockerfile$'
  - '.*Makefile.*$'

licenses:
  default:
    copyright: 'Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences, Germany (https://www.gfz-potsdam.de)'
    spdx-identifier: 'Apache-2.0'
  Software:
    copyright: 'Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences, Germany (https://www.gfz-potsdam.de)'
    spdx-identifier: 'Apache-2.0'
    files:
      - '.*\.txt$'
      - '.*\.md$'
      - '.*\.yml$'
      - '.*\.gitignore'
      - '.*\.gitmodules'
      - '.*\.py$'
      - '.*\.sh$'
      - '.*Dockerfile$'
      - '.*\.css$'
      - '.*\.js$'
      - '.*\.ts$'
      - '.*\.vue$'
